# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-testnet-sepolia        # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"
#     - chain-name: ethereum-mainnet                # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"
# ==========================================================================
staging-settings:
  rpcs:
    # @review using mainnets or testnets for staging
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
    - chain-name: polygon-mainnet
      url: https://polygon-bor-rpc.publicnode.com
    - chain-name: arbitrum-mainnet
      url: https://arbitrum-one-rpc.publicnode.com
    - chain-name: optimism-mainnet
      url: https://opt-mainnet.g.alchemy.com/v2/YOUR_API_KEY
    - chain-name: base-mainnet
      url: https://base-mainnet.g.alchemy.com/v2/YOUR_API_KEY
    - chain-name: avalanche-mainnet
      url: https://avalanche-c-chain-rpc.publicnode.com

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
    - chain-name: polygon-mainnet
      url: https://polygon-bor-rpc.publicnode.com
    - chain-name: arbitrum-mainnet
      url: https://arbitrum-one-rpc.publicnode.com
    - chain-name: optimism-mainnet
      url: https://opt-mainnet.g.alchemy.com/v2/YOUR_API_KEY
    - chain-name: base-mainnet
      url: https://base-mainnet.g.alchemy.com/v2/YOUR_API_KEY
    - chain-name: avalanche-mainnet
      url: https://avalanche-c-chain-rpc.publicnode.com
